name: Automatic lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test format
        run: clang-format --dry-run -ferror-limit=1 --Werror --verbose -i *.c src/*.c src/*.h

  two-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check limit of arguments per function
        run: ruby -e 'raise (File.read("./src/3bc_header.h").delete("\n").squeeze(" ").scan(/[a-z0-9_]+\([a-z0-9\*,_ ]+\);/i).select {|f| f.count(",") > 2}.first or exit)'
